name: overseer
description: Personal command-driven assistant for automation and self-evolving systems.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Voice and audio libraries
  speech_to_text: ^6.4.0
  flutter_tts: ^4.1.0

  # HTTP and GPT API interaction
  http: ^1.0.0

  # File and ZIP handling
  path_provider: ^2.1.1
  archive: ^3.5.0